### ISSUE TITLE
推理出错

### ISSUE THREAD

**Issue by ddzz0210** [ssbuild/moss_finetuning#11]
运行infer_ptuning.py 报错：
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in matmul_248_kernel:21                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 
('2-.-0-.-0-aced2afef9a9131c1822ef1dc83cefd3-d6252949da17ceb5f3a278a70250af13-3b85c7bef5f0a641282f3b73af50f599-14de7de5c4da5794c8ca14e7e41a122d-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078d
fc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.int32, torch.float16, torch.float16, torch.int32, torch.int32, 
'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (256, 64, 32, 8), (True, True, True, True, True, True, (False, True), (True, False), (True, False), (False,
False), (False, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (True, False)))

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /hy-tmp/finetune/infer_ptuning.py:34 in <module>                                                 │
│                                                                                                  │
│   31 │                                                                                           │
│   32 │   model = pl_model.get_llm_model()                                                        │
│   33 │   query = "<|Human|>: 你好<eoh>\n<|MOSS|>:"                                               │
│ ❱ 34 │   response = model.chat(tokenizer, query,  max_length=2048,                               │
│   35 │   │   │   │   │   │     eos_token_id=config.eos_token_id,                                 │
│   36 │   │   │   │   │   │     do_sample=True, top_p=0.7, temperature=0.95,                      │
│   37 │   │   │   │   │   │     )                                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py:27 in decorate_context        │
│                                                                                                  │
│    24 │   │   @functools.wraps(func)                                                             │
│    25 │   │   def decorate_context(*args, **kwargs):                                             │
│    26 │   │   │   with self.clone():                                                             │
│ ❱  27 │   │   │   │   return func(*args, **kwargs)                                               │
│    28 │   │   return cast(F, decorate_context)                                                   │
│    29 │                                                                                          │
│    30 │   def _wrap_generator(self, func):                                                       │

 /hy-tmp/finetune/models/moss_model.py:104 in chat                                                │
│                                                                                                  │
│   101 │   │   kwargs.update(self.extra_param.param)                                              │
│   102 │   │   tokens = tokenizer.batch_encode_plus([self.extra_param.prefix + text], return_te   │
│   103 │   │   input_ids, attention_mask = tokens['input_ids'], tokens['attention_mask']          │
│ ❱ 104 │   │   outputs = self.chat_inner(input_ids, attention_mask,**kwargs)                      │
│   105 │   │   preds = tokenizer.batch_decode(outputs)                                            │
│   106 │   │   res = self.postprocess_remove_prefix(preds[0])                                     │
│   107 │   │   return res                                                                         │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py:27 in decorate_context        │
│                                                                                                  │
│    24 │   │   @functools.wraps(func)                                                             │
│    25 │   │   def decorate_context(*args, **kwargs):                                             │
│    26 │   │   │   with self.clone():                                                             │
│ ❱  27 │   │   │   │   return func(*args, **kwargs)                                               │
│    28 │   │   return cast(F, decorate_context)                                                   │
│    29 │                                                                                          │
│    30 │   def _wrap_generator(self, func):                                                       │
│                                                                                                  │
│ /hy-tmp/finetune/models/moss_model.py:152 in chat_inner                                          │
│                                                                                                  │
│   149 │   │                                                                                      │
│   150 │   │   past_key_values = None                                                             │
│   151 │   │   for i in range(int(max_iterations)):                                               │
│ ❱ 152 │   │   │   logits, past_key_values = self.infer_(input_ids if i == 0 else new_generated   │
│   153 │   │   │   │   │   │   │   │   │   │   │   │     past_key_values)                         │
│   154 │   │   │                                                                                  │
│   155 │   │   │   if i == 0:                                                                     │
│                                                                                                  │
│ /hy-tmp/finetune/models/moss_model.py:241 in infer_                                              │
│                                                                                                  │
│   238 │   def infer_(self, input_ids, attention_mask, past_key_values):                          │
│   239 │   │   inputs = {"input_ids": input_ids, "attention_mask": attention_mask, "past_key_va   │
│   240 │   │   with torch.no_grad():                                                              │
│ ❱ 241 │   │   │   outputs = self.forward(**inputs,return_dict=True)                              │
│   242 │   │   return outputs.logits, outputs.past_key_values                                     │
│   243                                                                                            │
│   244                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/modeling_moss.py:673 in     │
│ forward                                                                                          │
│                                                                                                  │
│   670 │   │   """                                                                                │
│   671 │   │   return_dict = return_dict if return_dict is not None else self.config.use_return   │
│   672 │   │                                                                                      │
│ ❱ 673 │   │   transformer_outputs = self.transformer(                                            │
│   674 │   │   │   input_ids,                                                                     │
│   675 │   │   │   past_key_values=past_key_values,                                               │
│   676 │   │   │   attention_mask=attention_mask,                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1194 in _call_impl             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/modeling_moss.py:543 in     │
│ forward                                                                                          │
│                                                                                                  │
│   540 │   │   │   │   │   head_mask[i],                                                          │
│   541 │   │   │   │   )                                                                          │
│   542 │   │   │   else:                                                                          │
│ ❱ 543 │   │   │   │   outputs = block(                                                           │
│   544 │   │   │   │   │   hidden_states=hidden_states,                                           │
│   545 │   │   │   │   │   layer_past=layer_past,                                                 │
│   546 │   │   │   │   │   attention_mask=attention_mask,                                         │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1194 in _call_impl             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/modeling_moss.py:268 in     │
│ forward                                                                                          │
│                                                                                                  │
│   265 │   ) -> Union[Tuple[torch.Tensor], Optional[Tuple[torch.Tensor, Tuple[torch.FloatTensor   │
│   266 │   │   residual = hidden_states                                                           │
│   267 │   │   hidden_states = self.ln_1(hidden_states)                                           │
│ ❱ 268 │   │   attn_outputs = self.attn(                                                          │
│   269 │   │   │   hidden_states=hidden_states,                                                   │
│   270 │   │   │   layer_past=layer_past,                                                         │
│   271 │   │   │   attention_mask=attention_mask,                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1194 in _call_impl             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/modeling_moss.py:162 in     │
│ forward                                                                                          │
│                                                                                                  │
│   159 │   │   Tuple[torch.Tensor, Tuple[torch.Tensor]],                                          │
│   160 │   │   Optional[Tuple[torch.Tensor, Tuple[torch.Tensor], Tuple[torch.Tensor, ...]]],      │
│   161 │   ]:                                                                                     │
│ ❱ 162 │   │   qkv = self.qkv_proj(hidden_states)                                                 │
│   163 │   │   # TODO(enijkamp): factor out number of logical TPU-v4 cores or make forward pass   │
│   164 │   │   mp_num = 4                                                                         │
│   165 │   │   qkv_split = qkv.reshape(qkv.shape[:-1] + (mp_num, -1))                             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1194 in _call_impl             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/quantization.py:369 in      │
│ forward                                                                                          │
│                                                                                                  │
│   366 │                                                                                          │
│   367 │   def forward(self, x):                                                                  │
│   368 │   │   out_shape = x.shape[:-1] + (self.outfeatures,)                                     │
│ ❱ 369 │   │   out = QuantLinearFunction.apply(x.reshape(-1, x.shape[-1]), self.qweight, self.s   │
│   370 │   │   │   │   │   │   │   │   │   │   self.qzeros, self.g_idx, self.bits, self.maxq)     │
│   371 │   │   out = out + self.bias if self.bias is not None else out                            │
│   372 │   │   return out.reshape(out_shape)                                                      │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/cuda/amp/autocast_mode.py:105 in decorate_fwd       │
│                                                                                                  │
│   102 │   │   │   │   with autocast(enabled=False):                                              │
│   103 │   │   │   │   │   return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))    │
│   104 │   │   │   else:                                                                          │
│ ❱ 105 │   │   │   │   return fwd(*args, **kwargs)                                                │
│   106 │   return decorate_fwd                                                                    │
│   107                                                                                            │
│   108                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/quantization.py:281 in      │
│ forward                                                                                          │
│                                                                                                  │
│   278 │   @staticmethod                                                                          │
│   279 │   @custom_fwd(cast_inputs=torch.float16)                                                 │
│   280 │   def forward(ctx, input, qweight, scales, qzeros, g_idx, bits, maxq):                   │
│ ❱ 281 │   │   output = matmul248(input, qweight, scales, qzeros, g_idx, bits, maxq)              │
│   282 │   │   ctx.save_for_backward(qweight, scales, qzeros, g_idx)                              │
│   283 │   │   ctx.bits, ctx.maxq = bits, maxq                                                    │
│   284 │   │   return output                                                                      │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/quantization.py:250 in      │
│ matmul248                                                                                        │
│                                                                                                  │
│   247 │   output = torch.empty((input.shape[0], qweight.shape[1]), device='cuda', dtype=torch.   │
│   248 │   grid = lambda META: (                                                                  │
│   249 │   triton.cdiv(input.shape[0], META['BLOCK_SIZE_M']) * triton.cdiv(qweight.shape[1], ME   │
│ ❱ 250 │   matmul_248_kernel[grid](input, qweight, output,                                        │
│   251 │   │   │   │   │   │   │   scales, qzeros, g_idx,                                         │
│   252 │   │   │   │   │   │   │   input.shape[0], qweight.shape[1], input.shape[1], bits, maxq   │
│   253 │   │   │   │   │   │   │   input.stride(0), input.stride(1),                              │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/custom_autotune.py:89 in    │
│ run                                                                                              │
│                                                                                                  │
│    86 │   │   │   │   # prune configs                                                            │
│    87 │   │   │   │   pruned_configs = self.prune_configs(kwargs)                                │
│    88 │   │   │   │   bench_start = time.time()                                                  │
│ ❱  89 │   │   │   │   timings = {config: self._bench(*args, config=config, **kwargs)             │
│    90 │   │   │   │   │   │   │   for config in pruned_configs}                                  │
│    91 │   │   │   │   bench_end = time.time()                                                    │
│    92 │   │   │   │   self.bench_time = bench_end - bench_start                                  │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/custom_autotune.py:89 in    │
│ <dictcomp>                                                                                       │
│                                                                                                  │
│    86 │   │   │   │   # prune configs                                                            │
│    87 │   │   │   │   pruned_configs = self.prune_configs(kwargs)                                │
│    88 │   │   │   │   bench_start = time.time()                                                  │
│ ❱  89 │   │   │   │   timings = {config: self._bench(*args, config=config, **kwargs)             │
│    90 │   │   │   │   │   │   │   for config in pruned_configs}                                  │
│    91 │   │   │   │   bench_end = time.time()                                                    │
│    92 │   │   │   │   self.bench_time = bench_end - bench_start                                  │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/custom_autotune.py:71 in    │
│ _bench                                                                                           │
│                                                                                                  │
│    68 │   │   try:                                                                               │
│    69 │   │   │   # In testings using only 40 reps seems to be close enough and it appears to    │
│    70 │   │   │   # PyTorch also sets fast_flush to True, but I didn't see any speedup so I'll   │
│ ❱  71 │   │   │   return triton.testing.do_bench(kernel_call, rep=40)                            │
│    72 │   │   except triton.compiler.OutOfResources:                                             │
│    73 │   │   │   return float('inf')                                                            │
│    74                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/triton/testing.py:143 in do_bench                         │
│                                                                                                  │
│   140 │   """                                                                                    │
│   141 │                                                                                          │
│   142 │   # Estimate the runtime of the function                                                 │
│ ❱ 143 │   fn()                                                                                   │
│   144 │   torch.cuda.synchronize()                                                               │
│   145 │   start_event = torch.cuda.Event(enable_timing=True)                                     │
│   146 │   end_event = torch.cuda.Event(enable_timing=True)                                       │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/deep_training/nlp/models/moss/custom_autotune.py:67 in    │
│ kernel_call                                                                                      │
│                                                                                                  │
│    64 │   │   │   if config.pre_hook:                                                            │
│    65 │   │   │   │   config.pre_hook(self.nargs)                                                │
│    66 │   │   │   self.hook(args)                                                                │
│ ❱  67 │   │   │   self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages,   │
│    68 │   │   try:                                                                               │
│    69 │   │   │   # In testings using only 40 reps seems to be close enough and it appears to    │
│    70 │   │   │   # PyTorch also sets fast_flush to True, but I didn't see any speedup so I'll   │
│ in matmul_248_kernel:43                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered

**Comment by ddzz0210** [comment]
上面的问题解决了，换个环境就ok
但是推理的结果是这样的：
<|Human|>: 你好<eoh>
<|MOSS|>:  返回:  <|Human|>: 你好 <eoh> 
<|MOSS|>: Sorry bad luckyjunctionalitieshipmentsystematicserverwidely speaking illogicality inherentness unfairnessinesseselflessnessesearchingLYricsencephalopathyoso far away from realityigningredients missing altogether lackingsomething elseworldly experienceabilityalityankingtonspaceoutspacedownwardly tunneledowntypecastingrationary against nature obviousnessespectacularly addictednesseson behalfivenessesterday eveningimeologicalnessesourcefulnessesuppressionistorytellingtypedefinitionallyismobilementogethernessesafety level security blanketednessESuranceoftestosterone injections dynicallymphaticitylationnellettespeedilyticsensemblelementwiselyticulatezzaionnairekeepersshipswreckersemblance thereof uniquenessesotericnessesheetherednessesomewhat usable Ironclad immunityvginityousefulnessescientificallyspeaking inertiaosityessorially speaking garbage disposal manualizationistsitutionally speaking capacity mechanismocracyologyologically speaking orderlinesseserveable Conceptualizednesserythingyieldingnessessentially indistinguishable parserimonyously disputable validityating vsatilityility belongingnessessentialsityclingularly speakingcapacityicityoteriousnessessementsynthesisally speaking capabilityitanceitismatchinglysticksleriously speakingactivityivitytherapistically speaking goodness graciousnessesincerelyzingerousnessesimilarity between two sides falling asleepmidnightmaresqueernessesistanceagainst biasnesseshipwreckershipwrecker descendantshipmateshipmentalogymaticality assumptionistically homogeneousnesssegmentation fault syndrome semiconductoriformity meterianshipsterhoodsleeve incorporated into society Capitalistic behaviorismscreening laws enforcement mechanismsanismpowerlessnessescience fiction universeshipbuildershipyards shipyard workersSHIPwrighting history preservationistshipwarehouse operatorshipwarehouseshousing costs incurredby virtue of owning property rightsowshipsicleomorphicineffective functioning duelling systemsignificant amountsìotto padsilveringredientsexisting infrastructure vocabulary usagetershipwreckershipwreckershipyardsworker beekeeping industry Incorporatedinto mainstream media outletstedirectory database server side effectsivenumbering systematicalityntaxical correctnessionsmithsonianesquelihoodsourcedictorianterytainingementropyataliciousnesseserving ability theoretically speaking only everthelesssonorityrieserializable complexityityritic acidity levelsetting up routinesortilegeousnessesystematically speaking circumscribednessesystematicity itselfisticalisticsettingsupwardsreaching completion phase shiftagewaywardly tripshooting boardwalkeductionisticitybinoculars telescopic visionarityithmeticitystylishly lithography
<|Human|>: 你好 <eoh> 
<|MOSS|>: Sorry bad luckyjunctionalitieshipmentsystematicserverwidely speaking illogicality inherentness unfairnessinesseselflessnessesearchingLYricsencephalopathyoso far away from realityigningredients missing altogether lackingsomething elseworldly experienceabilityalityankingtonspaceoutspacedownwardly tunneledowntypecastingrationary against nature obviousnessespectacularly addictednesseson behalfivenessesterday eveningimeologicalnessesourcefulnessesuppressionistorytellingtypedefinitionallyismobilementogethernessesafety level security blanketednessESuranceoftestosterone injections dynicallymphaticitylationnellettespeedilyticsensemblelementwiselyticulatezzaionnairekeepersshipswreckersemblance thereof uniquenessesotericnessesheetherednessesomewhat usable Ironclad immunityvginityousefulnessescientificallyspeaking inertiaosityessorially speaking garbage disposal manualizationistsitutionally speaking capacity mechanismocracyologyologically speaking orderlinesseserveable Conceptualizednesserythingyieldingnessessentially indistinguishable parserimonyously disputable validityating vsatilityility belongingnessessentialsityclingularly speakingcapacityicityoteriousnessessementsynthesisally speaking capabilityitanceitismatchinglysticksleriously speakingactivityivitytherapistically speaking goodness graciousnessesincerelyzingerousnessesimilarity between two sides falling asleepmidnightmaresqueernessesistanceagainst biasnesseshipwreckershipwrecker descendantshipmateshipmentalogymaticality assumptionistically homogeneousnesssegmentation fault syndrome semiconductoriformity meterianshipsterhoodsleeve incorporated into society Capitalistic behaviorismscreening laws enforcement mechanismsanismpowerlessnessescience fiction universeshipbuildershipyards shipyard workersSHIPwrighting history preservationistshipwarehouse operatorshipwarehouseshousing costs incurredby virtue of owning property rightsowshipsicleomorphicineffective functioning duelling systemsignificant amountsìotto padsilveringredientsexisting infrastructure vocabulary usagetershipwreckershipwreckershipyardsworker beekeeping industry Incorporatedinto mainstream media outletstedirectory database server side effectsivenumbering systematicalityntaxical correctnessionsmithsonianesquelihoodsourcedictorianterytainingementropyataliciousnesseserving ability theoretically speaking only everthelesssonorityrieserializable complexityityritic acidity levelsetting up routinesortilegeousnessesystematically speaking circumscribednessesystematicity itselfisticalisticsettingsupwardsreaching completion phase shiftagewaywardly tripshooting boardwalkeductionisticitybinoculars telescopic visionarityithmeticitystylishly lithography
<|Human|>: 推荐五部科幻电影<eoh>
<|MOSS|>:  返回:  <|Human|>: 你好  <eoh>  
<|MOSS|>: Sorry bad luckyjunctionalitieshipmentsystematicserverwidely speaking illogicality inherentness unfairnessinesseselflessnessesearchingLYricsencephalopathyoso far away from realityigningredients missing altogether lackingsomething elseworldly experienceabilityalityankingtonspaceoutspacedownwardly tunneledowntypecastingrationary against nature obviousnessespectacularly addictednesseson behalfivenessesterday eveningimeologicalnessesourcefulnessesuppressionistorytellingtypedefinitionallyismobilementogethernessesafety level security blanketednessESuranceoftestosterone injections dynicallymphaticitylationnellettespeedilyticsensemblelementwiselyticulatezzaionnairekeepersshipswreckersemblance thereof uniquenessesotericnessesheetherednessesomewhat usable Ironclad immunityvginityousefulnessescientificallyspeaking inertiaosityessorially speaking garbage disposal manualizationistsitutionally speaking capacity mechanismocracyologyologically speaking orderlinesseserveable Conceptualizednesserythingyieldingnessessentially indistinguishable parserimonyously disputable validityating vsatilityility belongingnessessentialsityclingularly speakingcapacityicityoteriousnessessementsynthesisally speaking capabilityitanceitismatchinglysticksleriously speakingactivityivitytherapistically speaking goodness graciousnessesincerelyzingerousnessesimilarity between two sides falling asleepmidnightmaresqueernessesistanceagainst biasnesseshipwreckershipwrecker descendantshipmateshipmentalogymaticality assumptionistically homogeneousnesssegmentation fault syndrome semiconductoriformity meterianshipsterhoodsleeve incorporated into society Capitalistic behaviorismscreening laws enforcement mechanismsanismpowerlessnessescience fiction universeshipbuildershipyards shipyard workersSHIPwrighting history preservationistshipwarehouse operatorshipwarehouseshousing costs incurredby virtue of owning property rightsowshipsicleomorphicineffective functioning duelling systemsignificant amountsìotto padsilveringredientsexisting infrastructure vocabulary usagetershipwreckershipwreckershipyardsworker beekeeping industry Incorporatedinto mainstream media outletstedirectory database server side effectsivenumbering systematicalityntaxical correctnessionsmithsonianesquelihoodsourcedictorianterytainingementropyataliciousnesseserving ability theoretically speaking only everthelesssonorityrieserializable complexityityritic acidity levelsetting up routinesortilegeousnessesystematically speaking circumscribednessesystematicity itselfisticalisticsettingsupwardsreaching completion phase shiftagewaywardly tripshooting boardwalkeductionisticitybinoculars telescopic visionarityithmeticitystylishly lithography
<|Human|>: 推荐五部科幻电影 <eoh> 
<|MOSS|>: Recommendations for beginners starters moviegoers who want movies genreually speaking additively cohesive themematterialityouthful scenerywriting purposesoriginality sakefulnessesamples taken caretakerlessons learned lessonsouchingtonsanityoshikawaitella fantasticitieseparate occasionspiecemealnessessemblementariespaceflight attendant sinkingtonuousnessesolving problems Solving problemmaticalitytokensizeroomednessespecially craftedsmanshipmanshipibility degree Celsius degrees Fahrenheit equivalentsubstantialityudoceanicusumoimummedicationaryieldsuranceirafternoon tea partytimezoneontaneousnesseservices provideressingature spamming servicable harmony achieved by meanshiftting gravitylessnessesensitivity reactions sensitivityivitiesectionalizeiturefficeinationary accreditation status quo antecedureunityencyernalized regulationally equivalent theretoforensic analysis routineslyticalityotentiary\_\_paying attentioninyellowucedancellorium chloridehexagoneselectivityeuipmentideographic representationativeativesetting up shopkeeper confluence nounoselectedivityBVillettowingershipwreckage nitrous oxidenitrogenated technologynickel ionsnisolationismoving forward momentum generationally speaking volumeumesunterialistshipwreckednesseservationistshipwreckednesseservedimentationary talebooklets containing information about older than usual bookshelterednesseservationistshipwreckednesseservingeredifferenceicultyiesterified storage unitaryculuscularly speaking reversible magnification magnitudeultyuatednessessemblymanifestationary style guidebookscontaining information about how much money spentmoney laundering activity lifecycle managementistryotalitarianismdcriticalitydtimescaleheightened awarenessawarenessrahousing overthrow sickeningly sweetenednesseservingnessesourcefulnessesuppressionistutyoutube video clips showing footage snippetsomebody else inside joketershipwreckednessesessionally speaking freshest possible outcome Mrs./acletta bootstrapkitchenettechesapeake Bay Bridgeportraitureshipwreckednessesoundlessly inclinednesses depending upon availability of sufficient funds BParserrorpronely expensive housing units leased premisesharecropping paradigmatically speaking oldest livingardshipcraftsmanship mistreatment prevention strategylevelsafely integrated into society Global warming potential calculation site diagrammaticALLY speaking infiniteinitylatable membership cardholder unionized bloodthirstinesseshipwreckednesseshipwreckednessesourcefulnessesuppressionist dyphasisomiculousnessesystematically speaking copyrights violation motoring techniquesetted forthrightly Speaking termsiteshowever expressedly contrived situationseries creatoritativeleeing behind barsataristician


这是什么原因呀

**Comment by ssbuild** [comment]
是推理的官方权重还是自己微调的？  有没有修改层数？

**Comment by ddzz0210** [comment]
> 是推理的官方权重还是自己微调的？ 有没有修改层数？

用ptv2微调，然后运行infer_ptuning.py 没有修改层数

**Comment by ddzz0210** [comment]
> 是推理的官方权重还是自己微调的？ 有没有修改层数？

微调之后，adapter_model.bin文件只有5.3M，是不是训练过程的问题

**Comment by ssbuild** [comment]
ptv2 加载权重有bug， 0.1.8 fixed
